#!/bin/bash


# set up both monitors
# NOTE: this must be done before polybar
xrandr --output HDMI-1 --primary --mode 1920x1080 --rotate normal --output HDMI-2 --mode 1920x1080 --rotate normal --left-of HDMI-1
# Per monitor workspaces
## Use "bspc query -M to get the ID of the monitor"
## The assumption for this machine is that there will always be two monitors connected:
#if [ "$(bspc query -M | wc -l)" -eq "2"]; then
#	bspc monitor $(bspc query -M | sed -n 2p) -d 1 2 3 4
#	bspc monitor $(bspc query -M | sed -n 1p) -d 5 6 7 8
#fi
bspc monitor HDMI-2 -d 1 2 3 4
bspc monitor HDMI-1 -d 5 6 7 8

# Polybar(s)
## kill any existing instances
killall -q polybar
## wait until the processes have been shut down
while pgrep -u $UID -x polybar >/dev/null; do sleep 1; done
## lauch polybar for both monitors
#polybar rechts &
#polybar links &
#for m in $(polybar --list-monitors | cut -d":" -f1); do
#	MONITOR=$m polybar --reload rechts &
#done
MONITOR=HDMI-1 polybar --reload rechts &
MONITOR=HDMI-2 polybar --reload links &

xsetroot -cursor_name left_ptr
sxhkd &



bspc config border_width   2
bspc config window_gap     2

bspc config split_ratio    0.62 
bspc config focus_follows_pointer true 
bspc config pointer_modifier      mod1 

bspc config automatic_scheme      spiral 


